"""Initial migration

Revision ID: 384b0c2f1f96
Revises: 
Create Date: 2026-01-06 19:05:31.356298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384b0c2f1f96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('PESSOA_FISICA', 'PESSOA_JURIDICA', name='tipoparticipante'), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=True),
    sa.Column('cpf_hash', sa.String(length=64), nullable=True),
    sa.Column('cpf_criptografado', sa.Text(), nullable=True),
    sa.Column('categoria_pf', sa.Enum('CIRURGIAO_DENTISTA', 'AUXILIAR_TECNICO', 'ESTUDANTE', 'PESQUISADOR', 'CIDADAO', 'OUTRO', name='categoriaparticipantepf'), nullable=True),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('cnpj_hash', sa.String(length=64), nullable=True),
    sa.Column('cnpj_criptografado', sa.Text(), nullable=True),
    sa.Column('natureza_entidade', sa.Enum('CONSELHO_REGIONAL', 'ASSOCIACAO_CLASSE', 'SINDICATO', 'INSTITUICAO_ENSINO', 'CENTRO_PESQUISA', 'EMPRESA_PRIVADA', 'ORGAO_PUBLICO', 'ONG', 'OUTRO', name='naturezaentidadepj'), nullable=True),
    sa.Column('nome_responsavel_legal', sa.String(length=255), nullable=True),
    sa.Column('cpf_responsavel_hash', sa.String(length=64), nullable=True),
    sa.Column('cpf_responsavel_criptografado', sa.Text(), nullable=True),
    sa.Column('email_criptografado', sa.Text(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('consentimento_lgpd', sa.DateTime(), nullable=False),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_participante_tipo_criado', 'participantes', ['tipo', 'criado_em'], unique=False)
    op.create_index('idx_participante_uf_tipo', 'participantes', ['uf', 'tipo'], unique=False)
    op.create_index(op.f('ix_participantes_cnpj_hash'), 'participantes', ['cnpj_hash'], unique=False)
    op.create_index(op.f('ix_participantes_cpf_hash'), 'participantes', ['cpf_hash'], unique=False)
    op.create_index(op.f('ix_participantes_criado_em'), 'participantes', ['criado_em'], unique=False)
    op.create_index(op.f('ix_participantes_id'), 'participantes', ['id'], unique=False)
    op.create_index(op.f('ix_participantes_tipo'), 'participantes', ['tipo'], unique=False)
    op.create_index(op.f('ix_participantes_uf'), 'participantes', ['uf'], unique=False)
    op.create_table('contribuicoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.Enum('CEO', 'CPEO', name='documentoconsulta'), nullable=False),
    sa.Column('titulo_capitulo', sa.String(length=500), nullable=False),
    sa.Column('secao', sa.String(length=500), nullable=True),
    sa.Column('artigo', sa.String(length=100), nullable=False),
    sa.Column('paragrafo_inciso_alinea', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.Enum('ALTERACAO', 'INCLUSAO', 'EXCLUSAO', 'COMENTARIO', name='tipocontribuicao'), nullable=False),
    sa.Column('texto_proposto', sa.Text(), nullable=False),
    sa.Column('fundamentacao', sa.Text(), nullable=False),
    sa.Column('publicada', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contribuicao_doc_artigo', 'contribuicoes', ['documento', 'artigo'], unique=False)
    op.create_index('idx_contribuicao_publicada_criado', 'contribuicoes', ['publicada', 'criado_em'], unique=False)
    op.create_index('idx_contribuicao_tipo_doc', 'contribuicoes', ['tipo', 'documento'], unique=False)
    op.create_index(op.f('ix_contribuicoes_criado_em'), 'contribuicoes', ['criado_em'], unique=False)
    op.create_index(op.f('ix_contribuicoes_documento'), 'contribuicoes', ['documento'], unique=False)
    op.create_index(op.f('ix_contribuicoes_id'), 'contribuicoes', ['id'], unique=False)
    op.create_index(op.f('ix_contribuicoes_participante_id'), 'contribuicoes', ['participante_id'], unique=False)
    op.create_index(op.f('ix_contribuicoes_publicada'), 'contribuicoes', ['publicada'], unique=False)
    op.create_index(op.f('ix_contribuicoes_tipo'), 'contribuicoes', ['tipo'], unique=False)
    op.create_table('protocolos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_protocolo', sa.String(length=30), nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=10), nullable=False),
    sa.Column('total_contribuicoes', sa.Integer(), nullable=False),
    sa.Column('contribuicoes_ids', sa.JSON(), nullable=True),
    sa.Column('criado_em_brasilia', sa.DateTime(), nullable=False),
    sa.Column('criado_em_utc', sa.DateTime(), nullable=False),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('email_enviado', sa.DateTime(), nullable=True),
    sa.Column('email_confirmado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_protocolo_documento_criado', 'protocolos', ['documento', 'criado_em_brasilia'], unique=False)
    op.create_index('idx_protocolo_participante_criado', 'protocolos', ['participante_id', 'criado_em_brasilia'], unique=False)
    op.create_index(op.f('ix_protocolos_criado_em_brasilia'), 'protocolos', ['criado_em_brasilia'], unique=False)
    op.create_index(op.f('ix_protocolos_documento'), 'protocolos', ['documento'], unique=False)
    op.create_index(op.f('ix_protocolos_id'), 'protocolos', ['id'], unique=False)
    op.create_index(op.f('ix_protocolos_numero_protocolo'), 'protocolos', ['numero_protocolo'], unique=True)
    op.create_index(op.f('ix_protocolos_participante_id'), 'protocolos', ['participante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protocolos_participante_id'), table_name='protocolos')
    op.drop_index(op.f('ix_protocolos_numero_protocolo'), table_name='protocolos')
    op.drop_index(op.f('ix_protocolos_id'), table_name='protocolos')
    op.drop_index(op.f('ix_protocolos_documento'), table_name='protocolos')
    op.drop_index(op.f('ix_protocolos_criado_em_brasilia'), table_name='protocolos')
    op.drop_index('idx_protocolo_participante_criado', table_name='protocolos')
    op.drop_index('idx_protocolo_documento_criado', table_name='protocolos')
    op.drop_table('protocolos')
    op.drop_index(op.f('ix_contribuicoes_tipo'), table_name='contribuicoes')
    op.drop_index(op.f('ix_contribuicoes_publicada'), table_name='contribuicoes')
    op.drop_index(op.f('ix_contribuicoes_participante_id'), table_name='contribuicoes')
    op.drop_index(op.f('ix_contribuicoes_id'), table_name='contribuicoes')
    op.drop_index(op.f('ix_contribuicoes_documento'), table_name='contribuicoes')
    op.drop_index(op.f('ix_contribuicoes_criado_em'), table_name='contribuicoes')
    op.drop_index('idx_contribuicao_tipo_doc', table_name='contribuicoes')
    op.drop_index('idx_contribuicao_publicada_criado', table_name='contribuicoes')
    op.drop_index('idx_contribuicao_doc_artigo', table_name='contribuicoes')
    op.drop_table('contribuicoes')
    op.drop_index(op.f('ix_participantes_uf'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_tipo'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_id'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_criado_em'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_cpf_hash'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_cnpj_hash'), table_name='participantes')
    op.drop_index('idx_participante_uf_tipo', table_name='participantes')
    op.drop_index('idx_participante_tipo_criado', table_name='participantes')
    op.drop_table('participantes')
    # ### end Alembic commands ###
